deployment:
  name: nginx-deploy
  namespace: aks-train-smoke
  labels:
    app: nginx-deploy
    version: v1
  selectorLabels:
    app: nginx-pod
    version: v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    agentpool: aksapipool
  containers:
  - name: nginx-app
    image: akstrnacr.azurecr.io/nginx:alpine
    imagePullPolicy: IfNotPresent
    memoryRequest: "250Mi"
    cpuRequest: "100m"
    memoryLimit: "500Mi"
    cpuLimit: "200m"
    containerPorts: [80]    
service:
  name: nginx-svc
  namespace: aks-train-smoke
  selector:
    app: nginx-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  
    
    
